import {
  Building2,
  ChartColumn,
  CircleHelp,
  Clock,
  Code2,
  CreditCard,
  Eye,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Mail,
  MapPin,
  MessageCircle,
  Package,
  Palette,
  PenLine,
  Phone,
  Plug,
  RefreshCw,
  Rocket,
  Search,
  Send,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Store,
  Truck,
  Users,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { IconKey } from '../../content/types'

export const icons: Record<IconKey, LucideIcon> = {
  store: Store,
  'building-2': Building2,
  'layout-dashboard': LayoutDashboard,
  palette: Palette,
  package: Package,
  'shopping-cart': ShoppingCart,
  'credit-card': CreditCard,
  truck: Truck,
  'chart-column': ChartColumn,
  'circle-help': CircleHelp,
  mail: Mail,
  phone: Phone,
  send: Send,
  'message-circle': MessageCircle,
  'map-pin': MapPin,
  clock: Clock,
  sparkles: Sparkles,
  smartphone: Smartphone,
  plug: Plug,
  'life-buoy': LifeBuoy,
  search: Search,
  'pen-line': PenLine,
  'code-2': Code2,
  rocket: Rocket,
  users: Users,
  eye: Eye,
  'shield-check': ShieldCheck,
  layers: Layers,
  'refresh-cw': RefreshCw,
  zap: Zap,
}

export const getIcon = (key: IconKey): LucideIcon => icons[key]
